### ISSUE TITLE
Return output

### ISSUE THREAD

**Issue by danieledesantis** [Surbma/surbma-yoast-breadcrumb-shortcode#1]
Hi,
this is a very good plugin, but I would suggest a change:

The shortcode echoes the breadcrumb instead of returning it (line 39).
For this reason, the breadcrumb is always before the content of the current post/page, even if you add the shortcode at the end of the content.

According to Wordpress documentation:
>a shortcode should never produce output of any kind. Shortcode functions should return the text that is to be used to replace the shortcode.

In my fork I store the output inside a variable and the return it, so the breadcrumb is displayed exactly where the shortcode is:
```
$output = yoast_breadcrumb( $before, $after, false );
return $output;
```

Setting the third parameter to false (it is true by default) prevents the function from printing the value (see wordpress-seo/frontend/class-breadcrumb.php)

Hope this will help!
Daniele

**Comment by Surbma** [comment]
Hi @danieledesantis,

you are absolutely right about everything. I created this plugin years ago and in a rush. But no excuse, it was a bad code.

I have fixed it and the new release is coming soon. :)

Thank you for your support!

**Comment by danieledesantis** [comment]
Great, glad I could help!
:)
